import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import CustomerProvider from '@/providers/customer-provider'
import { headers } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const subdomain = headers().get('host')?.split('.')[0] || ''

  return (
    <html lang="en">
      <CustomerProvider subdomain={subdomain}>
        <body className={inter.className}>{children}</body>
      </CustomerProvider>
    </html>
  )
}
